### ISSUE TITLE
StaticCommand - dependency injection

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#281]
Since the static command uses static methods, we cannot do dependency injection easily.
We should allow to call also instance methods from the `staticCommand` binding. The class which contains the method would be instantiated for every command and this could be extended by IoC/DI.

Also, we should introduce the `StaticCommandHandlerBase` class and the `IStaticCommandHandler` interface which will have the `Context` property to allow to interact with the HTTP request. This property would by injected by the framework automatically. 

It will be optional to implement this interface, I think we can allow static command targets in any class. 

However, to keep things secure, any method called from the binding will have to be marked with the `AllowStaticCommand` attribute.

**Comment by exyi** [comment]
It makes sense to allow DI for staticCommand, but there is a problem with your solution. When a instance method in ViewModel is called, it just deserializes the VM and then invokes a method on it and there is not a point where to inject the dependencies, as the constructor is invoked by deserializer. I'd not like to disable (nor cripple) the instance method, because they can sometimes be very convenient.

Perhaps it would make sense to learn the serializer to inject dependencies to contsructor -- it will solve this issue and as a bonus it will be possible to deserialize nested viewmodels with dependencies.

**Comment by tomasherceg** [comment]
We are talking about staticCommand, there should be no deserialization of viewmodel involved.

Technically, the method called by staticCommand can be in the viewmodel, and then Init, Load and PreRender methods won't be fired, and the properties won't be loaded. But that's not a problem and we can display some warning to let the user know that the best practise is to place this method to another class.

**Comment by exyi** [comment]
Practically, it is often the case -- probably all the times I have seen static command really used, it was a an instance method. And you always have to deserialize the parameters anyway, so there is always a deserialization involved. The problem I tried to expose is that you can't use that easily the `StaticCommandHandlerBase` if the method you are calling is an instance one.

**Comment by tomasherceg** [comment]
Deserialization of parameters is not an issue, I don't want to dependency inject the parameters.

```
public class OrdersHandler : IStaticCommandHandlerBase
{
    // this can be injected too, depends on the container configuration
    public ILogger Log { get; set; }

    public OrdersHandler(/* this should be injected */ OrderService orderService)
    {
        ...
    }

    [AllowStaticCommand]
    public void ProcessOrder(/* nothing to inject here */ OrderDTO order) 
    {
       ...
    }

}
```

**Comment by djanosik** [comment]
Static commands do not use static methods. When you try that you run into an exception (`Could not resolve identifier 'StaticCommand'.`). They are always instance methods and it should be possible to enable dependency injection. JSON.NET allows to populate existing objects. 

Nested view models with dependencies feel like a mess to me. You would also need to initialize the nested model automatically. Would it be possible?

BTW: When I execute a static command, the `args` array contains the whole view model. So, there is a deserialization of VM involved. What's the difference from classic commands? Is it just about how the response is sent?

**Comment by tomasherceg** [comment]
They originally used static methods (and not instance ones) and if they do not support them now, it is a bug that should be fixed. Maybe this stopped working during migration to 1.1 because I am using it in several apps and it works.
Also, the static command shouldn't send the whole viewmodel to the server. It should only send the arguments which should be evaluated on the client side. If it sends the whole viewmodel to the server, again, it is a bug that should be fixed. The whole point of static commands is to exchange only the data which are really necessary, which is a must-have feature in larger apps.

This functionality is apparently not tested quite well, so we should put a lot of our attention here. I wonder whether there are any other things about static commands which I am not aware of. :-)

Nested viewmodels already work with DI and the child viewmodels are resolved (typically using property injection mechanism of the container). Even their `Context` properties are injected automatically by the framework.

**Comment by djanosik** [comment]
It would make sense to me to allow only static "static commands" on view models; and instance "static commands" only on `IStaticCommandHandler`. Because when you use instance "static command" on view model it's executed in the context of VM and you may expect it to be loaded.

**Comment by tomasherceg** [comment]
Good point. To prevent confusion from partially loaded viewmodels (which can really be a pain), we should enforce that the "instance static command" would be allowed only on `IStaticCommandHandler`.

**Comment by exyi** [comment]
Static commands of course works with static commands, they are just not resolved from scope parameter by the resolver - so you have to type `ViewModel.SomeCommand()`.
Instance static commands work exactly the same way as static static commands, the `this` parameter is just passed as any other parameter, it has no special meaning, technically it work exactly the same like static  methods.
It does not send the entire view model to the server, it only sends the parameters, including the possible `this` parameter. So it send the entire viewModel iff you call it on root viewModel, it may be completely reasonable in some situations IMO, but it is your choice. It is also reasonable to use it on parts of the viewmodel, something like `GetEntireText()` on `ArticleInfo`.

Just a note, the tests will not help at all, we are not talking now about bugs but about flaws in the design. We'd write the tests to match these flaws so they will be completely useless, we would just have to rewrite them with fixing these flaws, so it will be two times more expansive. The discussion can help, hopefully :).

**Comment by djanosik** [comment]
Thanks for clarifying, it makes sense.

**Comment by tomasherceg** [comment]
OK, I had a call with @exyi and we had clarified some things. 

I think that the current situation with the `_this` argument being transferred together with the parameters, is quite confusing becasue the `staticCommand` should be stateless. Also, the problem is that this is a totally undocumented behavior, as the documentation states that `staticCommand` can be used on static methods only.

I think that we should change the behavior and make a breaking change here. Better now than later. 
If someone is using the `staticCommand` on an instance method and rely on the `_this` parameter, he should change the method to the static one and add the `_this` as a method argument.

I want to make the `staticCommand` to be absolutely clear about what is being transferred - "here are the arguments, here is the return value, and that's it". 
Because if we keep the current behavior and the user calls an instance method on the root viewModel (the most common scenario) using the staticCommand, the whole viewModel is transferred and the main advantage of the staticCommand is destroyed (not completely, because there is no control tree construction etc., but still, the same amount of data is uploaded which is bad).

**Comment by tomasherceg** [comment]
I'll review the changes required on our projects, and I'll decide in a few days whether I want to introduce this breaking change or not.

**Comment by exyi** [comment]
resolved in #416
