### ISSUE TITLE
DotVVM extension generates wrong namespace

### ISSUE THREAD

**Issue by ppech** [riganti/dotvvm#654]
Extension generates viewmodel namespace with "Assembly name" instead of "Default namespace".

- Visual Studio 2017
- project is DotVVM for .NET Core
- project name and assembly name is MYPROJECT.App
- default namespace MYPROJECT
- generated namespace is "MYPROJECT.App.ViewModels..."

**Comment by quigamdev** [comment]
Thank you for the report. I have reported this issue to our VS team. I expect that this should be resolved in the next release of DotVVM Extension for Visual Studio.

**Comment by Mylan719** [comment]
I have tested the issue on DotVVM Extension version 2.4.182.0 both on 2019 and 2017 variants. The Extension behaves correctly when creating a ViewModel, a View + ViewModel and a Control code-behind. However when creating a Markup Control  + code-behind it still incorrectly uses Assembly name. This needs to be fixed.

**Comment by Mylan719** [comment]
New item wizard for creating Markup Control + code-behind now uses correct Default namespace. The issue should be fixed with next release. (2.4.183.0)
